config/routes.rb
ParisRbCassandra::Application.routes.draw do
  resources :heart_beats

  resources :people
  root 'people#index'

end

app/models/concerns/cequel_concern.rb
module CequelConcern
    extend ActiveSupport::Concern
    #This is because uuids will not get correctly seralized
    def read_attribute_for_serialization(n)
      n == "id" ? attributes[n].to_s : attributes[n]
    end
    
    def to_param
      self.id.to_s
    end
end

app/models/heart_beat.rb
# -*- encoding : utf-8 -*-
class HeartBeat
  include Cequel::Record
  include CequelConcern
  belongs_to :person

  key :id, :uuid, auto: true
  column :heart_beat, :timestamp
  column :intensity, :int

end

app/models/person.rb
# -*- encoding : utf-8 -*-
class Person
  include Cequel::Record
  include CequelConcern
  has_many :heart_beats
  
  key :id, :uuid, auto: true
  column :name, :text

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heart_beats_controller.rb
class HeartBeatsController < ApplicationController
  before_action :set_heart_beat, only: [:show, :edit, :update, :destroy]

  # GET /heart_beats
  # GET /heart_beats.json
  def index
    @heart_beats = HeartBeat.all
  end

  # GET /heart_beats/1
  # GET /heart_beats/1.json
  def show
  end

  # GET /heart_beats/new
  def new
    raise "How can we have a hear beat withtout a person ?" if Person.count == 0
    @heart_beat = HeartBeat.new
    @heart_beat.person = Person.first 
  end

  # GET /heart_beats/1/edit
  def edit
  end

  # POST /heart_beats
  # POST /heart_beats.json
  def create
    heart_beat= DateTime.new(params["heart_beat"]["heart_beat(1i)"].to_i,
                             params["heart_beat"]["heart_beat(2i)"].to_i,
                             params["heart_beat"]["heart_beat(3i)"].to_i,
                             params["heart_beat"]["heart_beat(4i)"].to_i,
                             params["heart_beat"]["heart_beat(5i)"].to_i)
    @heart_beat = HeartBeat.new({heart_beat: heart_beat, intensity:  params["heart_beat"]["intensity"].to_i})
    @heart_beat.person = Person.first

    respond_to do |format|
      if @heart_beat.save
        format.html { redirect_to @heart_beat, notice: 'Heart beat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @heart_beat }
      else
        format.html { render action: 'new' }
        format.json { render json: @heart_beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heart_beats/1
  # PATCH/PUT /heart_beats/1.json
  def update
    respond_to do |format|
      if @heart_beat.update(heart_beat_params)
        format.html { redirect_to @heart_beat, notice: 'Heart beat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @heart_beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heart_beats/1
  # DELETE /heart_beats/1.json
  def destroy
    @heart_beat.destroy
    respond_to do |format|
      format.html { redirect_to heart_beats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heart_beat
      @heart_beat = HeartBeat[Person.first.id.to_s].find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heart_beat_params
      params.require(:heart_beat).permit(:heart_beat, :intensity)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heart_beats_helper.rb
module HeartBeatsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/heart_beats/_form.html.erb
<%= form_for(@heart_beat) do |f| %>
  <% if @heart_beat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heart_beat.errors.count, "error") %> prohibited this heart_beat from being saved:</h2>

      <ul>
      <% @heart_beat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heart_beat %><br>
    <%= f.datetime_select :heart_beat %>
  </div>
  <div class="field">
    <%= f.label :intensity %><br>
    <%= f.text_field :intensity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heart_beats/edit.html.erb
<h1>Editing heart_beat</h1>

<%= render 'form' %>

<%= link_to 'Show', @heart_beat %> |
<%= link_to 'Back', heart_beats_path %>

app/views/heart_beats/index.html.erb
<h1>Listing heart_beats</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Heart beat</th>
      <th>Intensity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @heart_beats.each do |heart_beat| %>
      <tr>
        <td>
          <%= heart_beat.id %>
        </td>
        <td><%= heart_beat.heart_beat %></td>
        <td><%= heart_beat.intensity %></td>
        <td><%= link_to 'Show', heart_beat %></td>
        <td><%= link_to 'Edit', edit_heart_beat_path(heart_beat) %></td>
        <td><%= link_to 'Destroy', heart_beat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Heart beat', new_heart_beat_path %>

app/views/heart_beats/new.html.erb
<h1>New heart_beat</h1>

<%= render 'form' %>

<%= link_to 'Back', heart_beats_path %>

app/views/heart_beats/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>id:</strong>
  <%= @heart_beat.id %>
</p>
<p>
  <strong>Heart beat:</strong>
  <%= @heart_beat.heart_beat %>
</p>

<p>
  <strong>Intensity:</strong>
  <%= @heart_beat.intensity %>
</p>

<%= link_to 'Edit', edit_heart_beat_path(@heart_beat) %> |
<%= link_to 'Back', heart_beats_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paris Rb Cassandra" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Paris Rb Cassandra" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>